name: Build Android APK

on:
  push:
    branches-ignore:
      - l10n_dev

jobs:
  check_commit_msg:
    outputs:
      commit_message: ${{ steps.get_message.outputs.message }}
    name: Check if the workflow has been disabled.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get commit message
        id: get_message
        run: |
          echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')"
          echo "message=\"$(git log --format=%B -n 1 ${{ github.event.after }} | tr '\n' ' ')\"" >> $GITHUB_ENV

  build:
    needs: check_commit_msg
    if: ${{ !contains( needs.check_commit_msg.outputs.commit_message, '!APK') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        buildtype: [Debug, Release]
        arch: [x86, x86_64, arm, arm64]
        qt_version: [6.0.0]
        include:
          - arch: x86
            long_arch: x86
            short_arch: x86
          - arch: x86_64
            long_arch: x86_64
            short_arch: x64
          - arch: arm
            long_arch: armeabi-v7a
            short_arch: arm
          - arch: arm64
            long_arch: arm64-v8a
            short_arch: arm64
          - buildtype: Debug
            lowercase_buildtype: debug
          - buildtype: Release
            lowercase_buildtype: release

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Display Workflow Information
      run: |
        echo "Build Type: ${{ matrix.buildtype }}, Architecture: ${{ matrix.long_arch }}"

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache-${{ matrix.buildtype }}-${{ matrix.arch }}-${{ matrix.qt_version }}

    - name: Installing Qt - ${{ matrix.arch }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        target: android
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21d

    - name: Download Dependencies
      run: |
        sudo apt install -y ninja-build
        cd ./libs
        QV2RAY_LIBS=android QV2RAY_LIBS_ARCH="${{ matrix.short_arch }}" ./setup-libs.sh
        QV2RAY_LIBS=tools ./setup-libs.sh
        
    - name: Build Qv2ray
      run: |
        cd 3rdparty
        git clone https://github.com/KDAB/android_openssl
        cd ..
        mkdir build
        cd build
        $Qt6_DIR/android_${{ matrix.long_arch }}/bin/qt-cmake .. -GNinja \
          -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} \
          -DANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
          -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        cmake --build . --parallel $(nproc) --target apk
    - name: Build APK
      if: false
      run: |
        cd build/
        androiddeployqt --output ./android-build/ --input ./android_deployment_settings.json --${{ matrix.lowercase_buildtype }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Qv2ray.${{ github.sha }}.Android-${{ matrix.long_arch }}.qt${{ matrix.qt_version }}-${{ matrix.buildtype }}.zip
        path: build/android-build/build/outputs/apk/${{ matrix.lowercase_buildtype }}/
